teacher_index:
    path: /
    controller: App\Controller\TeacherController::index

teacher_show:
  path: /api/showTeachers
  controller: App\Controller\TeacherController::show

course_show:
  path: /api/showCourses
  controller: App\Controller\CourseController::show
