teacher_index:
    path: /
    controller: App\Controller\TeacherController::index

teacher_show:
  path: /api/showTeachers
  controller: App\Controller\TeacherController::show

course_show:
  path: /api/showCourses
  controller: App\Controller\CourseController::show

get_department:
  path: /api/getDepartment/{id}
  controller: App\Controller\DepartmentController::get

show_departments:
  path: /api/showDepartments
  controller: App\Controller\DepartmentController::show

show_sessions:
  path: /api/showSessions
  controller: App\Controller\SessionController::show

show_schedules:
  path: /api/showSchedules
  controller: App\Controller\ScheduleController::show

show_students:
  path: /api/showStudents
  controller: App\Controller\StudentController::show

show_reviews:
  path: /api/showReviews
  controller: App\Controller\ReviewController::show

new_review:
  path: /api/newReview
  controller: App\Controller\ReviewController::new
